PyAnnotePipeline:
  config:
    out_dir: ./pyannote_logs
    num_speakers: null
    min_speakers: null
    max_speakers: null
    use_oracle_clustering: false
    use_oracle_segmentation: false
    use_float16: false
